### PR TITLE
More reliable check if /usr/lib/sysimage/dnf/ database should be used

### LINKED ISSUE #197: Tracer has apparently stopped recognising updated packages in Fedora 38
Tracer has apparently stopped recognising updated-and-running packages in Fedora 38, except for the kernel.

Furthermore, I can't find python3-tracer between the packages available in fedora-bugzilla.

Related packages on Fedora:
tracer-common-0.7.9-1.fc38.noarch
python3-tracer-0.7.9-1.fc38.noarch

### PR DESCRIPTION
**Pull request by FrostyX**
Fix #197

### CODE REVIEW

**Comment by FrostyX** [comment]
@Conan-Kudo, can you please take a look if this breaks your SUSE use-case (https://github.com/FrostyX/tracer/commit/a70893a) or if it works just fine?

Without this patch, tracer finds nothing on F38.

**Review by Conan-Kudo — APPROVED** [review]

**Review by Conan-Kudo — CHANGES_REQUESTED** [review]
I'm confused why this breaks, does `os.path.exists()` not work with directories?

**Comment by FrostyX** [comment]
It does, but on my system, the `/usr/lib/sysimage/dnf` directory exists but it is empty (i.e. `/usr/lib/sysimage/dnf/history.sqlite` does not exist).

So I think if we want to use `/usr/lib/sysimage/dnf/history.sqlite` we should check it directly.

**Comment by Conan-Kudo** [comment]
Ah, I wonder why it exists on Fedora... But sure, makes sense.

**Comment by FrostyX** [comment]
Thank you for the review @Conan-Kudo

**Pull request merged**
