### PR TITLE
Fixes - #45 Report reboot for new kernels

### PR DESCRIPTION
**Pull request by sean797**
This compares `uname -r` to the directories in /lib/modules/, if a directory name in /lib/modules/ is bigger than `uname -r` a fake AffectedApplication is added for it.

### CODE REVIEW

**Comment by Klaas-** [comment]
I have a question - this would not catch situations in which I explicitly have set grub to not boot newest installed kernel. Is that on purpose?

**Comment by sean797** [comment]
@Klaas- That isn't something I thought about to be honest, but I would say yes its by design.

- If I have specifically set an old Kernel version to boot, I would still want that reminder. (maybe that's just me? )
- reading Grub config will likely be fairly complex

You should be able to use the ignore flag in applications.xml https://github.com/FrostyX/tracer/blob/master/data/applications.xml#L36 but i cannot seem to get it to work right now👎

**Comment by sean797** [comment]
Updated so it now respects the ignore flag in `applications.xml`.
Remember users can also store their own in `/etc/tracer/applications.xml` & `~/.config/tracer/applications.xml`

**Comment by Klaas-** [comment]
being able to turn if off when I really need to is enough for the usecase, thanks @sean797

**Pull request merged**
