### PR TITLE
rpm-python  instead rpm -ql

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by FrostyX** [comment]
Thank you,
definitely better than subprocess call.

Is it possible to find the list of files from package what is not installed? I.e. what would package provide if it was installed?

It would be nice to return them instead of `return []` which is just a workaround.

**Comment by xsuchy** [comment]
Hmm, in which situation we would be querying package which is not installed?

**Comment by FrostyX** [comment]
@xsuchy When you run some application and uninstall its package, tracer will not find it at all. That's because of this `return []`.

I think it would be nice to print those applications too. Sure, not under label "you should restart", but as some note "hey user, these applications has been uninstalled".

**Comment by xsuchy** [comment]
```
[root@dri/~]# rpm -q zsh
package zsh is not installed
[root@dri/~]# repoquery -l zsh |head
/etc/skel/.zshrc
/etc/zlogin
/etc/zlogout
/etc/zprofile
/etc/zshenv
/etc/zshrc
/usr/bin/zsh
/usr/lib64/zsh
/usr/lib64/zsh/5.0.7
/usr/lib64/zsh/5.0.7/zsh
```

And of course you may want to like to first query for that specific version user had. E.g repoquery -l zsh-5.0.7-4.fc21.x86_64

And repoquery itself is obsoleted and we should likely use 'dnf repoquery' put that does not support "-l" option. But I guess @ignatenkobrain can help here :)

**Comment by ignatenkobrain** [comment]
It works!
```
[brain@x1carbon tracer]$ sudo tracer -ea
You should restart:
  * Some applications using:
      sudo service docker restart

  * These applications manually:
      Xorg.bin
      abrt-applet
      accounts-daemon
      empathy-chat
      evolution
      evolution-addressbook-factory
      evolution-addressbook-factory-subprocess
      evolution-alarm-notify
      evolution-calendar-factory
      evolution-calendar-factory-subprocess
      evolution-source-registry
      firefox
      gdm
      gdm-session-wor
      gjs-console
      gnome-session
      gnome-settings-daemon
      gnome-shell
      gnome-shell-calendar-server
      gnome-software
      gnome-user-share-webdav
      goa-daemon
      gsd-printer
      ibus-x11
      packagekitd
      plugin-container
      seapplet
      tracker-extract
```

**Comment by FrostyX** [comment]
Changes looks beautiful. Much thanks.

**Pull request merged**
