### PR TITLE
if systemd is running then use systemctl

### PR DESCRIPTION
**Pull request by sean797**
I'm not sure why dist check was there in the first place but other dist's uses systemd so lets make it for for them :-)

This was added in #53

### CODE REVIEW

**Comment by TingPing** [comment]
> I'm not sure why dist check was there in the first place

If you hit show comments on the outdated diff you will see.

**Comment by sean797** [comment]
> If you hit show comments on the outdated diff you will see.

That comment was true up until F14, in F26 or max F27 service will disappear.

**Comment by TingPing** [comment]
Yea I saw no reason to keep that behavior anyway.

**Comment by FrostyX** [comment]
Yeah, you are right guys. Let's merge this. Thank you!

**Pull request merged**
